### ISSUE TITLE
sanity checks causing problems

### ISSUE THREAD

**Issue by accowa** [NOC-OI/msm-os#10]
There appears to be some issues with the integrity checks when appending data. Illustrated by this sequence:

```
msm_os send --file ./eORCA12_1d_grid_T_197601-197601.nc --bucket npd12-j001-test2 --append-dim time_counter --credentials /home/users/acc/NEMO_cylc/bin/mycreds -v tos_con -cs {"time_counter": 1, "x": 720, "y": 360}

msm_os send --file ./eORCA12_1d_grid_T_197602-197602.nc --bucket npd12-j001-test2 --append-dim time_counter --credentials /home/users/acc/NEMO_cylc/bin/mycreds -v tos_con -cs {"time_counter": 1, "x": 720, "y": 360}
```

The first command creates the bucket and writes 31 days of data to it. The second command should append 29 days of February data to the bucket but complains:

```
☁  msm_os ☁  |    WARNING | 2024-07-15 12:44:21 | Dimension time_counter has size 60, expected 31.
☁  msm_os ☁  |    WARNING | 2024-07-15 12:44:21 | Error found while trying to update file npd12-j001-test2/T1d/tos_con.zarr with time value of 1976-02-01T12:00:00.000000000: dimension mismatch. Error: Dimension time_counter has size 60, expected 31.
☁  msm_os ☁  |    WARNING | 2024-07-15 12:44:21 | Object store object npd12-j001-test2/T1d/tos_con.zarr will be rolled back to previous version
☁  msm_os ☁  |       INFO | 2024-07-15 12:44:41 | Object store object npd12-j001-test2/T1d/tos_con.zarr rolled back successfully.
```

and the bucket is left with 59 days worth of data in it. If I disable the checks by changing:

```diff
--- a/src/msm_os/object_store_handler.py
+++ b/src/msm_os/object_store_handler.py
 
@@ -359,7 +358,7 @@ def _send_variable(

         # Check data integrity
         try:
-            check_data_integrity(mapper, var, append_dim, ds_filepath)
+            check_data_integrity(mapper, var, append_dim, ds_filepath, "None")
```

Then repeating the sequence from scratch results in 60 time-levels (but the time_counter expected_size attribute is still set to 31).

There is an additional problem with the expected_size attribute which is not applied to the x and y dimensions since they don't have any associated metadata.

**Comment by soutobias** [comment]
@accowa , I apologize for the delay. I've been involved in several projects over the past two months and haven't had time to look at the issues.

I tested and fixed the problem related to sanity checks. I also improve the performance of the sanity checks. I merged the changes into the dev branch.

**Comment by accowa** [comment]
Thanks Tobias. Is there a reason you've left the issue open or is it ready to use?

**Comment by soutobias** [comment]
@accowa , it is ready to use. I forgot to close it 😅
