### ISSUE TITLE
skip sanity checks working but err.out reporting strange error

### ISSUE THREAD

**Issue by accowa** [NOC-OI/msm-os#15]
A serial task to write all 5d fields for eORCA12 for 1 month completed successfully inside 10 hours with the new -si flag active (still version 0.1.1?). At least it appears to have been successful but the slurm err file reports this warning message:

```
/home/users/acc/NEMO_cylc/etc/new_dev/src/msm_os/sanity_checks.py:328: RuntimeWarning: invalid value encountered in cast
  values = np.nan_to_num(values, nan=0, posinf=0, neginf=0).astype(np.uint32)
```
63 times.

Something in sanity_checks.py is still being called?
The bucket written was: `s3://npd12-j001-5d-1976`
```
s3cmd ls s3://npd12-j001-5d-1976/
                          DIR  s3://npd12-j001-5d-1976/T5d/
                          DIR  s3://npd12-j001-5d-1976/U5d/
                          DIR  s3://npd12-j001-5d-1976/V5d/
                          DIR  s3://npd12-j001-5d-1976/W5d/
                          DIR  s3://npd12-j001-5d-1976/icemod5d/
                          DIR  s3://npd12-j001-5d-1976/scalar5d/
```
job script: `/home/users/acc/NEMO_cylc/bin/si_5d_serial_mytransfer_to_os.sh`

**Comment by soutobias** [comment]
Hi @accowa , I forgot to include the skip in the calculate metadata part. So, although it was skipping the integrity checks, it was calculating the metadata. I just updated the code.
