### ISSUE TITLE
restrictions on bucket names

### ISSUE THREAD

**Issue by accowa** [NOC-OI/msm-os#3]
Apparently:

An error occurred (InvalidBucketName) when calling the CreateBucket operation: **S3 bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).**

not sure where that restriction is coming from since s3cmd seems happy with uppercase letters at least. Still it needs to be stated somewhere in the guidance notes to prevent others from falling foul.

**Comment by soutobias** [comment]
@accowa, according to https://docs.aws.amazon.com/prescriptive-guidance/latest/defining-bucket-names-data-lakes/faq.html#q5, there are indeed some restrictions on the bucket name:

`Only lowercase letters, numbers, dashes, and periods are allowed in S3 bucket names. Bucket names must be three to 63 characters long, start and end with a number or letter, and cannot be in IP address format. Names must also be globally unique. For S3 bucket paths, you can use uppercase letters, but we recommend using only lowercase letters. Paths can also include additional symbols, but we recommend that you only use underscores, dashes, slashes, and numbers.`

I added this information to the docstring part of the function `create_bucket` and `send`. And I also added this information to the [NEMO_CYLC project](https://github.com/NOC-OI/NEMO_cylc/blob/dev/cookbooks/instructions.md#transfer-to-os-notes).
